services:
  db:
    container_name: postgres_db
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
     - ./migrations/create.sql:/docker-entrypoint-initdb.d/create.sql
     - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-ads}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
  advertisements: 
    build: ./advertisements-storage
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy 
volumes:
  pg_data: