services:
  db:
    container_name: postgres_db
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
     - ./migrations/create.sql:/docker-entrypoint-initdb.d/create.sql
     - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-ads}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
  advertisements-storage: 
    build: ./advertisements-storage
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
  category-service: 
    build: ./category-service
    ports:
      - "8001:8001"
    environment:
      - STORAGE_ADDR=advertisements-storage:8000
    depends_on:
      - advertisements-storage
  search-service: 
    build: ./search-service
    ports:
      - "8002:8002"
    environment:
      - STORAGE_ADDR=advertisements-storage:8000
    depends_on:
      - advertisements-storage
  users-service: 
    build: ./users-service
    ports:
      - "8003:8003"
    environment:
      - STORAGE_ADDR=advertisements-storage:8000
    depends_on:
      - advertisements-storage
  ads-service:
    build: ./ads-service
    ports:
      - "8005:8005"
    environment:
      - STORAGE_ADDR=advertisements-storage:8000
    depends_on:
      - advertisements-storage
  api-gateway:
    build: ./api-gateway
    ports:
      - "8004:8004"
    environment: 
      - CATEGORY_SERVICE_ADDR=category-service:8001
      - SEARCH_SERVICE_ADDR=search-service:8002
      - USER_SERVICE_ADDR=users-service:8003
      - ADS_SERVICE_ADDR=ads-service:8005
    depends_on:
      - category-service
      - users-service
      - search-service
      - ads-service
volumes:
  pg_data: